FROM openjdk:19-jdk-alpine
WORKDIR /app
COPY target/mediapp-specialties-0.0.1-SNAPSHOT.jar mediapp-specialties-0.0.1-SNAPSHOT.jar
EXPOSE 8094
CMD [ "java", "-jar", "mediapp-specialties-0.0.1-SNAPSHOT.jar" ]
